---
services:
  api:
    build: .
    image: chatbot-backend:latest
    restart: unless-stopped
    deploy:
      replicas: 2
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - app_network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

networks:
  app_network:
    driver: bridge
  
volumes:
  caddy_data: